<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@2.0.3 .\static\models\spaceship.glb --transform
-->

<script lang="ts">
	import { Group } from 'three';
	import { T, forwardEventHandlers } from '@threlte/core';
	import { useGltf } from '@threlte/extras';

	export const ref = new Group();

	const gltf = useGltf('/models/spaceship-transformed.glb', { useDraco: true });

	gltf.then((model) => {
		function alphaFix(material: Record<string, unknown>) {
			material['transparent'] = true;
			material['alphaToCoverage'] = true;
			material['depthTest'] = true;
			material['depthWrite'] = true;
		}
		alphaFix(model.materials['spaceship_racer']);
		alphaFix(model.materials['cockpit']);
	});

	const component = forwardEventHandlers();
</script>

<T is={ref} dispose={false} {...$$restProps} bind:this={$component}>
	{#await gltf}
		<slot name="fallback" />
	{:then gltf}
		<T.Group scale={0.3}>
			<T.Mesh
				castShadow
				receiveShadow
				geometry={gltf.nodes.Cube001_spaceship_racer_0.geometry}
				material={gltf.materials.spaceship_racer}
			/>
			<T.Mesh
				castShadow
				receiveShadow
				geometry={gltf.nodes.Cube001_RExtr001_spaceship_racer_0.geometry}
				material={gltf.materials.spaceship_racer}
			/>
			<T.Mesh
				castShadow
				receiveShadow
				geometry={gltf.nodes.Cube001_RPanel001_spaceship_racer_0.geometry}
				material={gltf.materials.spaceship_racer}
			/>
			<T.Mesh
				castShadow
				receiveShadow
				geometry={gltf.nodes.Cube001_RPanel003_spaceship_racer_0.geometry}
				material={gltf.materials.spaceship_racer}
			/>
			<T.Mesh
				castShadow
				receiveShadow
				geometry={gltf.nodes.Cube001_RPanel003_RExtr_spaceship_racer_0.geometry}
				material={gltf.materials.spaceship_racer}
			/>
			<T.Mesh
				castShadow
				receiveShadow
				geometry={gltf.nodes.Cube001_RPanel003_RExtr001_spaceship_racer_0.geometry}
				material={gltf.materials.spaceship_racer}
			/>
			<T.Mesh
				castShadow
				receiveShadow
				geometry={gltf.nodes.Cube002_spaceship_racer_0.geometry}
				material={gltf.materials.spaceship_racer}
			/>
			<T.Mesh
				castShadow
				receiveShadow
				geometry={gltf.nodes.Cube003_spaceship_racer_0.geometry}
				material={gltf.materials.spaceship_racer}
			/>
			<T.Mesh
				castShadow
				receiveShadow
				geometry={gltf.nodes.Cube005_cockpit_0.geometry}
				material={gltf.materials.cockpit}
			/>
			<T.Mesh
				castShadow
				receiveShadow
				geometry={gltf.nodes.Cylinder002_spaceship_racer_0.geometry}
				material={gltf.materials.spaceship_racer}
			/>
			<T.Mesh
				castShadow
				receiveShadow
				geometry={gltf.nodes.Cylinder003_spaceship_racer_0.geometry}
				material={gltf.materials.spaceship_racer}
			/>
			<T.Mesh
				geometry={gltf.nodes.Cylinder004_spaceship_racer_0.geometry}
				material={gltf.materials.spaceship_racer}
			/>
			<T.Mesh geometry={gltf.nodes.Sphere_cockpit_0.geometry} material={gltf.materials.cockpit} />
		</T.Group>
	{:catch error}
		<slot name="error" {error} />
	{/await}

	<slot {ref} />
</T>
